"""
app/models/invitation.py — Invitation ORM Model

Handles invitations to join an organization. Contains a secure token that expires.
"""
import enum
import uuid
from datetime import datetime, timedelta
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.organization import Organization


class InvitationStatus(str, enum.Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    EXPIRED = "EXPIRED"


def _default_expiration():
    # Invitations expire 7 days after creation
    return datetime.now() + timedelta(days=7)


class Invitation(Base):
    __tablename__ = "invitations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Email of the user being invited (they might not have an account yet)
    email: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    
    # Cryptographically secure random token (e.g. generated by secrets.token_urlsafe)
    invitation_token: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)

    status: Mapped[InvitationStatus] = mapped_column(
        Enum(InvitationStatus, name="invitation_status_enum"),
        default=InvitationStatus.PENDING,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_default_expiration,
        nullable=False,
    )
    
    accepted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Relationships
    organization: Mapped["Organization"] = relationship("Organization", back_populates="invitations")

    def __repr__(self) -> str:
        return f"<Invitation org={self.organization_id!s:.8} email={self.email} status={self.status}>"
